apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    ecom.platform/version: {{ .Chart.AppVersion | quote }}
    ecom.platform/tier: edge
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "gateway.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "gateway.fullname" . }}
        eci.service: gateway
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        prometheus.io/scrape: "{{ .Values.metrics.enabled }}"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/path: "{{ .Values.metrics.path }}"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      priorityClassName: {{ .Values.scheduling.priorityClass | quote }}
      terminationGracePeriodSeconds: 30
      {{- with (include "gateway.nodeSelector" . | trim) }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "gateway.tolerations" . | trim) }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        {{- include "gateway.topologySpreadConstraints" . | nindent 8 }}
      containers:
        - name: gateway
          image: {{ include "gateway.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "gateway.fullname" . }}
          env:
            {{- include "gateway.extraEnv" . | nindent 12 }}
            {{- if .Values.envSecrets }}
            {{- range .Values.envSecrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
            {{- end }}
            {{- end }}
          livenessProbe:
            {{- include "gateway.probes.liveness" . | nindent 12 }}
          readinessProbe:
            {{- include "gateway.probes.readiness" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
