apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "review.fullname" . }}
  labels:
    {{- include "review.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- with .Values.extraConfig }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
