apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/part-of: ecom
    eci.phase: "6"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.observability.svc:9090
        isDefault: true
        jsonData:
          timeInterval: 15s
          httpMethod: POST
        editable: false

      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc:3100
        jsonData:
          maxLines: 1000
        editable: false

      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger-query.observability.svc:16686
        jsonData:
          tracesToLogs:
            datasourceUid: Loki
            tags: ['service', 'request_id']
          nodeGraph:
            enabled: true
        editable: false
