apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-root
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ecom
    eci.phase: "5"
    eci.role: root-application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ecom
  source:
    repoURL: https://github.com/mylab12345/Ecom-Site-Devops.git
    targetRevision: gitops/main
    path: argocd/applications
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
