apiVersion: v2
name: payment
description: E-Commerce payment microservice — 8006 — critical tier — Graviton ARM64
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - ecom
  - payment
  - microservices
  - graviton
  - critical
home: https://github.com/mylab12345/Ecom-Site-Devops
sources:
  - https://github.com/mylab12345/Ecom-Site-Devops
dependencies:
  - name: ecom-common
    version: 0.1.0
    repository: file://../ecom-common
maintainers:
  - name: platform-team
    email: platform@ecom.local
annotations:
  ecom.platform/service: payment
  ecom.platform/port: "8006"
  ecom.platform/tier: critical
